namespace Cyb3rPod
{
    public class EscapePodIntent
    {
        public string Oid { get; set; }
        public string Name { get; set; }
        public string Intent { get; set; }
        public string Utterance { get; set; }

        public EscapePodIntent(string name, string intent, string utternace)
        {
            this.Name = name;
            this.Intent = intent;
            this.Utterance = utternace;
        }

        public string ToJson()
        {
            string newIntentJson = "{";
            newIntentJson += string.Format("'intent':'{0}',", this.Intent);
            newIntentJson += "'description':'Intent generated by Cyb3rVector',";
            newIntentJson += "'extended_options':{'external_parser':true,'block_list':null},";
            newIntentJson += "'inversekeyphrases':null,";
            newIntentJson += "'inversekeyphrases':null,";
            newIntentJson += string.Format("'name':'{0}',", this.Name);
            newIntentJson += string.Format("'utterance_list':'{0}',", this.Utterance);
            newIntentJson += "'response_parameters':{" + string.Format("'final_intent':'{0}'", this.Intent) + "}";
            newIntentJson += "}";

            return newIntentJson.Replace("'", "\"");
        }
    }
}