// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: cybervector_proxy.proto

package cybervector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Unknown       MessageType = 0
	MessageType_Subscribed    MessageType = 1
	MessageType_Unsubscribed  MessageType = 2
	MessageType_KeepAlive     MessageType = 3
	MessageType_ProcessIntent MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Unknown",
		1: "Subscribed",
		2: "Unsubscribed",
		3: "KeepAlive",
		4: "ProcessIntent",
	}
	MessageType_value = map[string]int32{
		"Unknown":       0,
		"Subscribed":    1,
		"Unsubscribed":  2,
		"KeepAlive":     3,
		"ProcessIntent": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_cybervector_proxy_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_cybervector_proxy_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{0}
}

type ResponseMessage_ResponseCode int32

const (
	ResponseMessage_SUCCESS ResponseMessage_ResponseCode = 0
	ResponseMessage_FAILURE ResponseMessage_ResponseCode = 1
)

// Enum value maps for ResponseMessage_ResponseCode.
var (
	ResponseMessage_ResponseCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	ResponseMessage_ResponseCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x ResponseMessage_ResponseCode) Enum() *ResponseMessage_ResponseCode {
	p := new(ResponseMessage_ResponseCode)
	*p = x
	return p
}

func (x ResponseMessage_ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseMessage_ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cybervector_proxy_proto_enumTypes[1].Descriptor()
}

func (ResponseMessage_ResponseCode) Type() protoreflect.EnumType {
	return &file_cybervector_proxy_proto_enumTypes[1]
}

func (x ResponseMessage_ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseMessage_ResponseCode.Descriptor instead.
func (ResponseMessage_ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{3, 0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// keep alive stream interval in seconds,
	// requested from client, default 30 seconds
	KeepAlive int64 `protobuf:"varint,1,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetKeepAlive() int64 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{1}
}

type ProxyMessaage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Proxy Message Type enum
	MessageType MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=cybervector.MessageType" json:"message_type,omitempty"`
	// Proxy Message Json data
	MessageData string `protobuf:"bytes,2,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	// The named intent to respond with.
	IntentName string `protobuf:"bytes,3,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`
	// A list of parameters as parsed by the escape pod
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProxyMessaage) Reset() {
	*x = ProxyMessaage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyMessaage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMessaage) ProtoMessage() {}

func (x *ProxyMessaage) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMessaage.ProtoReflect.Descriptor instead.
func (*ProxyMessaage) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyMessaage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_Unknown
}

func (x *ProxyMessaage) GetMessageData() string {
	if x != nil {
		return x.MessageData
	}
	return ""
}

func (x *ProxyMessaage) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *ProxyMessaage) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    ResponseMessage_ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=cybervector.ResponseMessage_ResponseCode" json:"code,omitempty"`
	Message string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseMessage) GetCode() ResponseMessage_ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseMessage_SUCCESS
}

func (x *ResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InsertIntentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntentData string `protobuf:"bytes,1,opt,name=intent_data,json=intentData,proto3" json:"intent_data,omitempty"`
}

func (x *InsertIntentRequest) Reset() {
	*x = InsertIntentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertIntentRequest) ProtoMessage() {}

func (x *InsertIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertIntentRequest.ProtoReflect.Descriptor instead.
func (*InsertIntentRequest) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *InsertIntentRequest) GetIntentData() string {
	if x != nil {
		return x.IntentData
	}
	return ""
}

type InsertIntentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *ResponseMessage `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *InsertIntentResponse) Reset() {
	*x = InsertIntentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertIntentResponse) ProtoMessage() {}

func (x *InsertIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertIntentResponse.ProtoReflect.Descriptor instead.
func (*InsertIntentResponse) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *InsertIntentResponse) GetResponse() *ResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

type SelectIntentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterJson string `protobuf:"bytes,1,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
}

func (x *SelectIntentRequest) Reset() {
	*x = SelectIntentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectIntentRequest) ProtoMessage() {}

func (x *SelectIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectIntentRequest.ProtoReflect.Descriptor instead.
func (*SelectIntentRequest) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *SelectIntentRequest) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

type SelectIntentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response   *ResponseMessage  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	FilterJson string            `protobuf:"bytes,2,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	IntentData map[string]string `protobuf:"bytes,3,rep,name=intent_data,json=intentData,proto3" json:"intent_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SelectIntentResponse) Reset() {
	*x = SelectIntentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectIntentResponse) ProtoMessage() {}

func (x *SelectIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectIntentResponse.ProtoReflect.Descriptor instead.
func (*SelectIntentResponse) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *SelectIntentResponse) GetResponse() *ResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SelectIntentResponse) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

func (x *SelectIntentResponse) GetIntentData() map[string]string {
	if x != nil {
		return x.IntentData
	}
	return nil
}

type DeleteIntentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntentId string `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
}

func (x *DeleteIntentRequest) Reset() {
	*x = DeleteIntentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntentRequest) ProtoMessage() {}

func (x *DeleteIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntentRequest.ProtoReflect.Descriptor instead.
func (*DeleteIntentRequest) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteIntentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

type DeleteIntentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *ResponseMessage `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteIntentResponse) Reset() {
	*x = DeleteIntentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cybervector_proxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntentResponse) ProtoMessage() {}

func (x *DeleteIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cybervector_proxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntentResponse.ProtoReflect.Descriptor instead.
func (*DeleteIntentResponse) Descriptor() ([]byte, []int) {
	return file_cybervector_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteIntentResponse) GetResponse() *ResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_cybervector_proxy_proto protoreflect.FileDescriptor

var file_cybervector_proxy_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x79, 0x62, 0x65, 0x72,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65,
	0x65, 0x70, 0x5f, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x6e, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x9b, 0x02, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x61, 0x67,
	0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x4a, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x61,
	0x67, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x3d,
	0x0a, 0x0f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x94, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3d, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55,
	0x52, 0x45, 0x10, 0x01, 0x22, 0x36, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x14,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36,
	0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x84, 0x02, 0x0a, 0x14, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x3d,
	0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x79,
	0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2a, 0x5e, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x10, 0x03,
	0x12, 0x11, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x10, 0x04, 0x32, 0xb9, 0x03, 0x0a, 0x17, 0x43, 0x79, 0x62, 0x65, 0x72, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4a, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1d, 0x2e, 0x63,
	0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x79,
	0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x0b, 0x55,
	0x6e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x79,
	0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x79, 0x62, 0x65,
	0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x79,
	0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x56, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x20, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x79,
	0x62, 0x33, 0x72, 0x64, 0x6f, 0x67, 0x2f, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2d, 0x70, 0x6f,
	0x64, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x79, 0x62, 0x65, 0x72, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cybervector_proxy_proto_rawDescOnce sync.Once
	file_cybervector_proxy_proto_rawDescData = file_cybervector_proxy_proto_rawDesc
)

func file_cybervector_proxy_proto_rawDescGZIP() []byte {
	file_cybervector_proxy_proto_rawDescOnce.Do(func() {
		file_cybervector_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_cybervector_proxy_proto_rawDescData)
	})
	return file_cybervector_proxy_proto_rawDescData
}

var file_cybervector_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cybervector_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cybervector_proxy_proto_goTypes = []interface{}{
	(MessageType)(0),                  // 0: cybervector.MessageType
	(ResponseMessage_ResponseCode)(0), // 1: cybervector.ResponseMessage.ResponseCode
	(*SubscribeRequest)(nil),          // 2: cybervector.SubscribeRequest
	(*UnsubscribeRequest)(nil),        // 3: cybervector.UnsubscribeRequest
	(*ProxyMessaage)(nil),             // 4: cybervector.ProxyMessaage
	(*ResponseMessage)(nil),           // 5: cybervector.ResponseMessage
	(*InsertIntentRequest)(nil),       // 6: cybervector.InsertIntentRequest
	(*InsertIntentResponse)(nil),      // 7: cybervector.InsertIntentResponse
	(*SelectIntentRequest)(nil),       // 8: cybervector.SelectIntentRequest
	(*SelectIntentResponse)(nil),      // 9: cybervector.SelectIntentResponse
	(*DeleteIntentRequest)(nil),       // 10: cybervector.DeleteIntentRequest
	(*DeleteIntentResponse)(nil),      // 11: cybervector.DeleteIntentResponse
	nil,                               // 12: cybervector.ProxyMessaage.ParametersEntry
	nil,                               // 13: cybervector.SelectIntentResponse.IntentDataEntry
}
var file_cybervector_proxy_proto_depIdxs = []int32{
	0,  // 0: cybervector.ProxyMessaage.message_type:type_name -> cybervector.MessageType
	12, // 1: cybervector.ProxyMessaage.parameters:type_name -> cybervector.ProxyMessaage.ParametersEntry
	1,  // 2: cybervector.ResponseMessage.code:type_name -> cybervector.ResponseMessage.ResponseCode
	5,  // 3: cybervector.InsertIntentResponse.response:type_name -> cybervector.ResponseMessage
	5,  // 4: cybervector.SelectIntentResponse.response:type_name -> cybervector.ResponseMessage
	13, // 5: cybervector.SelectIntentResponse.intent_data:type_name -> cybervector.SelectIntentResponse.IntentDataEntry
	5,  // 6: cybervector.DeleteIntentResponse.response:type_name -> cybervector.ResponseMessage
	2,  // 7: cybervector.CyberVectorProxyService.Subscribe:input_type -> cybervector.SubscribeRequest
	3,  // 8: cybervector.CyberVectorProxyService.UnSubscribe:input_type -> cybervector.UnsubscribeRequest
	6,  // 9: cybervector.CyberVectorProxyService.InsertIntent:input_type -> cybervector.InsertIntentRequest
	8,  // 10: cybervector.CyberVectorProxyService.SelectIntents:input_type -> cybervector.SelectIntentRequest
	10, // 11: cybervector.CyberVectorProxyService.DeleteIntent:input_type -> cybervector.DeleteIntentRequest
	4,  // 12: cybervector.CyberVectorProxyService.Subscribe:output_type -> cybervector.ProxyMessaage
	4,  // 13: cybervector.CyberVectorProxyService.UnSubscribe:output_type -> cybervector.ProxyMessaage
	7,  // 14: cybervector.CyberVectorProxyService.InsertIntent:output_type -> cybervector.InsertIntentResponse
	9,  // 15: cybervector.CyberVectorProxyService.SelectIntents:output_type -> cybervector.SelectIntentResponse
	11, // 16: cybervector.CyberVectorProxyService.DeleteIntent:output_type -> cybervector.DeleteIntentResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cybervector_proxy_proto_init() }
func file_cybervector_proxy_proto_init() {
	if File_cybervector_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cybervector_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyMessaage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertIntentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertIntentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectIntentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectIntentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIntentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cybervector_proxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIntentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cybervector_proxy_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cybervector_proxy_proto_goTypes,
		DependencyIndexes: file_cybervector_proxy_proto_depIdxs,
		EnumInfos:         file_cybervector_proxy_proto_enumTypes,
		MessageInfos:      file_cybervector_proxy_proto_msgTypes,
	}.Build()
	File_cybervector_proxy_proto = out.File
	file_cybervector_proxy_proto_rawDesc = nil
	file_cybervector_proxy_proto_goTypes = nil
	file_cybervector_proxy_proto_depIdxs = nil
}
