// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extension.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Podextension {
  public static partial class PodExtension
  {
    static readonly string __ServiceName = "podextension.PodExtension";

    static readonly grpc::Marshaller<global::Podextension.UnaryReq> __Marshaller_podextension_UnaryReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Podextension.UnaryReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Podextension.UnaryResp> __Marshaller_podextension_UnaryResp = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Podextension.UnaryResp.Parser.ParseFrom);

    static readonly grpc::Method<global::Podextension.UnaryReq, global::Podextension.UnaryResp> __Method_Unary = new grpc::Method<global::Podextension.UnaryReq, global::Podextension.UnaryResp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unary",
        __Marshaller_podextension_UnaryReq,
        __Marshaller_podextension_UnaryResp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Podextension.ExtensionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PodExtension</summary>
    public abstract partial class PodExtensionBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Podextension.UnaryResp> Unary(global::Podextension.UnaryReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PodExtension</summary>
    public partial class PodExtensionClient : grpc::ClientBase<PodExtensionClient>
    {
      /// <summary>Creates a new client for PodExtension</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PodExtensionClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PodExtension that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PodExtensionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PodExtensionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PodExtensionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Podextension.UnaryResp Unary(global::Podextension.UnaryReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Unary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Podextension.UnaryResp Unary(global::Podextension.UnaryReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unary, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Podextension.UnaryResp> UnaryAsync(global::Podextension.UnaryReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Podextension.UnaryResp> UnaryAsync(global::Podextension.UnaryReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unary, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PodExtensionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PodExtensionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PodExtensionBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Unary, serviceImpl.Unary).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PodExtensionBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Unary, serviceImpl.Unary);
    }

  }
}
#endregion
