version: '3.7'
services:
  escape-pod-extension:
    build: .
    entrypoint:
      - "/cybervector-proxy"
    environment:
      - CYB3RVECTOR_PROXY_CLIENT_PORT=${CYB3RVECTOR_PROXY_CLIENT_PORT}
      - CYB3RVECTOR_PROXY_CLIENT_INSECURE=${CYB3RVECTOR_PROXY_CLIENT_RPC_INSECURE}
      - CYB3RVECTOR_PROXY_CLIENT_CLIENT_AUTHENTICATION=${CYB3RVECTOR_PROXY_CLIENT_CLIENT_AUTHENTICATION}

      - CYB3RVECTOR_PROXY_SERVER_PORT=${CYB3RVECTOR_PROXY_SERVER_PORT}
      - CYB3RVECTOR_PROXY_SERVER_INSECURE=${CYB3RVECTOR_PROXY_SERVER_INSECURE}
      - CYB3RVECTOR_PROXY_SERVER_CLIENT_AUTHENTICATION=${CYB3RVECTOR_PROXY_SERVER_CLIENT_AUTHENTICATION}
    expose:
      - "8089"
      - "8090"
    ports:
      - "8089:8089"
      - "8090:8090"